project:
  type: website
  output-dir: docs

website:
  title: "The Sound of All Them Witches - Merijn Dekker"
  navbar:
    right:
      - text: Home
        href: index.rmd
      - text: Album Analysis
        menu:
          - text: "Our Mother Electricity"
            href: OME.qmd
          - text: "Lightning At The Door"
            href: LATD.qmd
          - text: "Dying Surfer Meets His Maker"
            href: DSMHM.qmd
          - text: "Sleeping Through The War"
            href: STTW.qmd
          - text: "ATW"
            href: ATW.qmd
          - text: "Nothing as the Ideal"
            href: NATI.qmd
      - text: Cross-Album Analysis
        href: caanalysis.qmd

execute:
  echo: false
  warning: false
  message: false

format:
  html:
    code-fold: false
    theme: quartz